# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4msvIcJJeqe8whoW8bGtPPsnwbK3f-9

Reading data
"""

import pandas as pd

df = pd.read_csv("/content/sample_data/imdb_reviews.csv.csv")
print(df.head())

"""covert text to number using CountVectorizer"""

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['review'])  # النصوص
y = df['sentiment']  # التصنيفات

"""Naive Bayes model"""

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# تقسيم البيانات
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# تدريب النموذج
model = MultinomialNB()
model.fit(X_train, y_train)

# التقييم
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

"""Model testing"""

sample = ["The movie was absolutely wonderful!"]
sample_vec = vectorizer.transform(sample)
print(model.predict(sample_vec))